### ISSUE TITLE
Add community support (CONTRIBUTING.md, CODE_OF_CONDUCT.md, etc...)

### ISSUE THREAD

**Issue by KaanGaming** [alt03b1/BedrockVanillaTweaks#8]
I suggest you add some markdown files on how to contribute, code of conduct, a license, issue templates and pull request templates. Sometimes people don't know what they wanna type, issue templates and pull request templates are perfect for these. Licenses are for showing what's right to do while using program, both personal use or not. It may not be important fully, since this OSP is usually a list for bedrock edition vanilla tweaks. Contributing file and code of conduct is perfect for everyone. Users, contributors, collaborators, maintainers, and everyone else. Contributing.md usually explains how you can help the project, while code of conduct explains how you must act here.

**If you would like to add these if you think there will be more contributors in future, or even users, you can add CONTRIBUTING.md, CODE_OF_CONDUCT.md and issue templates.** Pull request template is optional, but I am not sure about LICENSE.md.

**Comment by KaanGaming** [comment]
Recently made a commit in my fork in branch **community-updates**, it contains the new CONTRIBUTING.md. If you are willing to commit the changes, feel free to review my guide to contributing. I'm always open to suggestions.
[Link to CONTRIBUTIONS.md](https://github.com/KaanGaming/BedrockVanillaTweaks/blob/community-updates/CONTRIBUTING.md) - [Link to the commit](https://github.com/KaanGaming/BedrockVanillaTweaks/commit/c6ac7f68270303320a528d2bf1b4152c735d941b)

**Comment by lithium-lx** [comment]
Hi KaanGaming,
As you might know, this is a very small project just by me and alt. I'm only interested in issue templates and maybe the LICENSE.md. A Contribution can be made by writing a issue, because at this moment we are only copying the vanilla tweaks, and if something misses/does not work, it's an issue that we can fix by ourselves(or the user writes a pull request, but this does not happen very often, so I don't think we need an template for that). The Code of Conduct is also unnecessary, all users just need to follow the [community guidelines by github](https://docs.github.com/en/github/site-policy/github-community-guidelines). Maybe I will write an general info for all people on this.

**Comment by KaanGaming** [comment]
Ah, I overcomplicated the project as it seems, Yeah, it is more likely that it is unnecessary to put code of conduct and contributing.md, thank you for the comment. I'm closing this issue now, but if you want otherwise, you can re-open it.
